(Dialog chetan
    (Components
        (SubLayout Layout1)
    )
    (Resources
        (.ResourceHints "Version:Creo4")
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.Layout
            (Grid
                (Rows 0)
                (Cols 1)
                Layout1
            )
        )
    )
)
(Layout Layout1
    (Components
        (Label mytext)
        (Label nameLable)
        (InputPanel name)
        (Label emailLable)
        (InputPanel email)
        (Label itemsLable)
        (OptionMenu items)
        (Separator Separator1)
        (Separator Separator1_copy)
        (PushButton submit)
        (PushButton cancel)
    )
    (Resources
        (mytext.Label "Hey, Welcome My App")
        (mytext.Alignment 0)
        (mytext.Resizeable True)
        (mytext.TopOffset 5)
        (mytext.BottomOffset 0)
        (mytext.LeftOffset 0)
        (mytext.RightOffset 0)
        (mytext.ForegroundColor 1)
        (mytext.FontSize 12.000000)
        (mytext.FontClass 5)
        (nameLable.Label "Enter Name:")
        (nameLable.Alignment 0)
        (nameLable.Resizeable True)
        (nameLable.TopOffset 0)
        (nameLable.BottomOffset 0)
        (nameLable.LeftOffset 10)
        (nameLable.RightOffset 0)
        (name.HelpText "Enter Name")
        (name.TopOffset 10)
        (name.BottomOffset 10)
        (name.LeftOffset 10)
        (name.RightOffset 10)
        (name.Gravity 1)
        (emailLable.Label "Enter Email:")
        (emailLable.Alignment 0)
        (emailLable.Resizeable True)
        (emailLable.TopOffset 0)
        (emailLable.BottomOffset 0)
        (emailLable.LeftOffset 10)
        (emailLable.RightOffset 0)
        (email.HelpText "Enter Emal")
        (email.TopOffset 10)
        (email.BottomOffset 10)
        (email.LeftOffset 10)
        (email.RightOffset 10)
        (itemsLable.Label "Select Item:")
        (itemsLable.Alignment 0)
        (itemsLable.Resizeable True)
        (itemsLable.TopOffset 0)
        (itemsLable.BottomOffset 0)
        (itemsLable.LeftOffset 0)
        (itemsLable.RightOffset 0)
        (items.SelectedNames "chetan")
        (items.GroupNames "chetan")
        (items.GroupLabels "sagar")
        (items.TopOffset 10)
        (items.BottomOffset 10)
        (items.LeftOffset 10)
        (items.RightOffset 10)
        (items.GroupItems "")
        (items.Integers 5 1 2 3 4)
        (items.Doubles 0.000000)
        (items.Strings "chetan" "hritik" "sahil" "pratik")
        (submit.Label "Enter")
        (submit.Columns 10)
        (submit.HelpText "This is Enter Button")
        (submit.Wrap True)
        (submit.Resizeable True)
        (submit.TopOffset 10)
        (submit.BottomOffset 5)
        (submit.LeftOffset 5)
        (submit.RightOffset 5)
        (submit.FontStyle 8)
        (submit.AlwaysOnTop True)
        (cancel.Label "cancel")
        (cancel.HelpText "click here to close the dialog")
        (cancel.Resizeable True)
        (cancel.TopOffset 10)
        (cancel.BottomOffset 5)
        (cancel.LeftOffset 5)
        (cancel.RightOffset 5)
        (.AttachLeft True)
        (.AttachRight True)
        (.AttachTop True)
        (.AttachBottom True)
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.Layout
            (Grid
                (Rows 0 0 0 0 0 0)
                (Cols 0 1)
                (Pos 1 2)
                mytext
                (Pos 2 1)
                nameLable
                (Pos 2 2)
                name
                (Pos 3 1)
                emailLable
                (Pos 3 2)
                email
                (Pos 4 1)
                itemsLable
                (Pos 4 2)
                items
                (Pos 5 1)
                Separator1
                (Pos 5 2)
                Separator1_copy
                (Pos 6 2)
                (Grid
                    (Rows 1)
                    (Cols 1 0)
                    submit cancel
                )
            )
        )
    )
)
